/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictionary;

import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class DictionaryMain extends javax.swing.JFrame {
    boolean change = false;

    /**
     * Creates new form DictionaryMain
     */
    public DictionaryMain() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pChoiceLayout = new javax.swing.JPanel();
        pEnglishVietnamese = new javax.swing.JPanel();
        btnSearchEnglish = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtEnglishSearch = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtVietnamese = new javax.swing.JTextArea();
        pVietnameseEnglish = new javax.swing.JPanel();
        btnSeachVietnamese = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        txtVietnameseSearch = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEnglish = new javax.swing.JTextArea();
        pAddEnglishVietnamese = new javax.swing.JPanel();
        btnAddEnglish = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtEnglishAdd = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtVietnamese1 = new javax.swing.JTextArea();
        pAddVietnameseEnglish = new javax.swing.JPanel();
        btnAddVietnamese = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        txtVietnameseAdd = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtEnglish1 = new javax.swing.JTextArea();
        pChoicePanel = new javax.swing.JPanel();
        cbbChoiceLayout = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(509, 500));

        pChoiceLayout.setLayout(new java.awt.CardLayout());

        btnSearchEnglish.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSearchEnglish.setText("Search");
        btnSearchEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEnglishActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("English"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEnglishSearch)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(txtEnglishSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("VietNamese"));

        txtVietnamese.setColumns(20);
        txtVietnamese.setRows(5);
        jScrollPane1.setViewportView(txtVietnamese);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pEnglishVietnameseLayout = new javax.swing.GroupLayout(pEnglishVietnamese);
        pEnglishVietnamese.setLayout(pEnglishVietnameseLayout);
        pEnglishVietnameseLayout.setHorizontalGroup(
            pEnglishVietnameseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEnglishVietnameseLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pEnglishVietnameseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pEnglishVietnameseLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pEnglishVietnameseLayout.setVerticalGroup(
            pEnglishVietnameseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEnglishVietnameseLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pEnglishVietnameseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pEnglishVietnameseLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnSearchEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pChoiceLayout.add(pEnglishVietnamese, "EnglishVietnamese");

        btnSeachVietnamese.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSeachVietnamese.setText("Search");
        btnSeachVietnamese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeachVietnameseActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Vietnamese"));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtVietnameseSearch)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(txtVietnameseSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("English"));

        txtEnglish.setColumns(20);
        txtEnglish.setRows(5);
        jScrollPane2.setViewportView(txtEnglish);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pVietnameseEnglishLayout = new javax.swing.GroupLayout(pVietnameseEnglish);
        pVietnameseEnglish.setLayout(pVietnameseEnglishLayout);
        pVietnameseEnglishLayout.setHorizontalGroup(
            pVietnameseEnglishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pVietnameseEnglishLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pVietnameseEnglishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pVietnameseEnglishLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSeachVietnamese, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pVietnameseEnglishLayout.setVerticalGroup(
            pVietnameseEnglishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pVietnameseEnglishLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pVietnameseEnglishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pVietnameseEnglishLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnSeachVietnamese, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pChoiceLayout.add(pVietnameseEnglish, "VietnameseEnglish");

        btnAddEnglish.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddEnglish.setText("Add");
        btnAddEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEnglishActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("English"));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEnglishAdd)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(txtEnglishAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("VietNamese"));

        txtVietnamese1.setColumns(20);
        txtVietnamese1.setRows(5);
        jScrollPane3.setViewportView(txtVietnamese1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pAddEnglishVietnameseLayout = new javax.swing.GroupLayout(pAddEnglishVietnamese);
        pAddEnglishVietnamese.setLayout(pAddEnglishVietnameseLayout);
        pAddEnglishVietnameseLayout.setHorizontalGroup(
            pAddEnglishVietnameseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddEnglishVietnameseLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pAddEnglishVietnameseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pAddEnglishVietnameseLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pAddEnglishVietnameseLayout.setVerticalGroup(
            pAddEnglishVietnameseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddEnglishVietnameseLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pAddEnglishVietnameseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pAddEnglishVietnameseLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnAddEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pChoiceLayout.add(pAddEnglishVietnamese, "AddEnglishVietnamese");

        btnAddVietnamese.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddVietnamese.setText("Add");
        btnAddVietnamese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVietnameseActionPerformed(evt);
            }
        });

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Vietnamese"));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtVietnameseAdd)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(txtVietnameseAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("English"));

        txtEnglish1.setColumns(20);
        txtEnglish1.setRows(5);
        jScrollPane4.setViewportView(txtEnglish1);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pAddVietnameseEnglishLayout = new javax.swing.GroupLayout(pAddVietnameseEnglish);
        pAddVietnameseEnglish.setLayout(pAddVietnameseEnglishLayout);
        pAddVietnameseEnglishLayout.setHorizontalGroup(
            pAddVietnameseEnglishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddVietnameseEnglishLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pAddVietnameseEnglishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pAddVietnameseEnglishLayout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddVietnamese, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pAddVietnameseEnglishLayout.setVerticalGroup(
            pAddVietnameseEnglishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddVietnameseEnglishLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pAddVietnameseEnglishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pAddVietnameseEnglishLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnAddVietnamese, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pChoiceLayout.add(pAddVietnameseEnglish, "AddVietnameseEnglish");

        getContentPane().add(pChoiceLayout, java.awt.BorderLayout.CENTER);

        cbbChoiceLayout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English-Vietnamese", "Vietnamese-English", "Add English-Vietnamese", "Add Vietnamese-English" }));
        cbbChoiceLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChoiceLayoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pChoicePanelLayout = new javax.swing.GroupLayout(pChoicePanel);
        pChoicePanel.setLayout(pChoicePanelLayout);
        pChoicePanelLayout.setHorizontalGroup(
            pChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pChoicePanelLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(cbbChoiceLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        pChoicePanelLayout.setVerticalGroup(
            pChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pChoicePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(cbbChoiceLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(pChoicePanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbChoiceLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChoiceLayoutActionPerformed
        int pos = cbbChoiceLayout.getSelectedIndex();
        CardLayout cl = (CardLayout) this.pChoiceLayout.getLayout();
        switch(pos){
            case 0: cl.show(pChoiceLayout, "EnglishVietnamese");break;
            case 1: cl.show(pChoiceLayout, "VietnameseEnglish");break;
            case 2: cl.show(pChoiceLayout, "AddEnglishVietnamese");break;
            case 3: cl.show(pChoiceLayout, "AddVietnameseEnglish");break;
        }
    }//GEN-LAST:event_cbbChoiceLayoutActionPerformed

    private void btnSearchEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEnglishActionPerformed
        EnglishVietnamese el = new EnglishVietnamese();
        el.readFileEL();
        String wordSearch = txtEnglishSearch.getText().trim();
        txtVietnamese.setText(el.searchEnglish(wordSearch));
        txtVietnamese.setEditable(false);
        
    }//GEN-LAST:event_btnSearchEnglishActionPerformed

    private void btnSeachVietnameseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeachVietnameseActionPerformed
        VietnameseEnglish ve = new VietnameseEnglish();
        ve.readFileVE();
        String wordSearch = txtVietnameseSearch.getText().trim();
        txtEnglish.setText(ve.searchVietnamese(wordSearch));
        txtEnglish.setEditable(false);
    }//GEN-LAST:event_btnSeachVietnameseActionPerformed

    private void btnAddEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEnglishActionPerformed
        if(txtEnglishAdd.getText().trim().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "English words not be empty");
            return;
        }
            
        else if(txtVietnamese1.getText().trim().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Vietnam words not be empty");
            return;
        }            
        EnglishVietnamese eV = new EnglishVietnamese();
        String key = txtEnglishAdd.getText().trim();
        String value = txtVietnamese1.getText().trim();
        eV.readFileEL();
//        if (eV.checkEV(key) == null) {
//            eV.addEnglishVietnamese(key, value);
//            JOptionPane.showMessageDialog(this, "Add words to successful dictionary.");  
//            txtEnglishAdd.setText("");
//            txtVietnamese1.setText("");
//            change = false;
//        }    
//            
//            
//        else{
//            if(change == false){
//                int r = JOptionPane.showConfirmDialog(this, "Word already exists, do you want to edit the data?", "Add", JOptionPane.YES_NO_OPTION);
//                if (r == JOptionPane.YES_OPTION){
//                    txtVietnamese1.setText(eV.checkEV(key));
//                    change = true;
//                }       
//            }
//            else {
//                eV.addEnglishVietnamese(key, value);
//                JOptionPane.showMessageDialog(this, "Add words to successful dictionary.");

//                change = false;
//            }
//            
//        }
        eV.AddEV(key, value);
        JOptionPane.showMessageDialog(this, "Add words to successful dictionary.");
        txtEnglishAdd.setText("");
        txtVietnamese1.setText("");
        
    }//GEN-LAST:event_btnAddEnglishActionPerformed

    private void btnAddVietnameseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVietnameseActionPerformed
        
        if(txtVietnameseAdd.getText().trim().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Vietnam words not be empty");
            return;
        }
            
        else if(txtEnglish1.getText().trim().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "English words not be empty");
            return;
        }            
        VietnameseEnglish vE = new VietnameseEnglish();
        String key = txtVietnameseAdd.getText().trim();
        String value = txtEnglish1.getText().trim();
        vE.readFileVE();
//        if (vE.checkVE(key) == null){     
//            vE.addVietnameseEnglish(key, value);
//            JOptionPane.showMessageDialog(this, "Add words to successful dictionary.");
//            change = false;
//        }
//        else{
//            if(change == false){
//                int r = JOptionPane.showConfirmDialog(this, "Word already exists, do you want to edit the data?", "Add", JOptionPane.YES_NO_OPTION);
//                if (r == JOptionPane.YES_OPTION){
//                    txtEnglish1.setText(vE.checkVE(key));
//                    change = true;
//                }       
//            }
//            else {
//                vE.addVietnameseEnglish(key, value);
//                JOptionPane.showMessageDialog(this, "Add words to successful dictionary.");
//                change = false;
//            }
//            
//        }
       vE.addVE(key, value);
        JOptionPane.showMessageDialog(this, "Add words to successful dictionary.");
        txtVietnameseAdd.setText("");
        txtEnglish1.setText("");
    }//GEN-LAST:event_btnAddVietnameseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DictionaryMain d = new DictionaryMain();
                d.setLocationRelativeTo(null);
                d.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEnglish;
    private javax.swing.JButton btnAddVietnamese;
    private javax.swing.JButton btnSeachVietnamese;
    private javax.swing.JButton btnSearchEnglish;
    private javax.swing.JComboBox<String> cbbChoiceLayout;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pAddEnglishVietnamese;
    private javax.swing.JPanel pAddVietnameseEnglish;
    private javax.swing.JPanel pChoiceLayout;
    private javax.swing.JPanel pChoicePanel;
    private javax.swing.JPanel pEnglishVietnamese;
    private javax.swing.JPanel pVietnameseEnglish;
    private javax.swing.JTextArea txtEnglish;
    private javax.swing.JTextArea txtEnglish1;
    private javax.swing.JTextField txtEnglishAdd;
    private javax.swing.JTextField txtEnglishSearch;
    private javax.swing.JTextArea txtVietnamese;
    private javax.swing.JTextArea txtVietnamese1;
    private javax.swing.JTextField txtVietnameseAdd;
    private javax.swing.JTextField txtVietnameseSearch;
    // End of variables declaration//GEN-END:variables
}
